<a href="https://colab.research.google.com/github/mkaraca25/Python_Numpy_Pandas_Matplotlib_Seaborn/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NUMPY

In [3]:
##Neden NUMPY bilimsel hesaplamalarda kullanilir.
import numpy as np
import time
start_time=time.time() 
A=np.arange(1000000)
A**2
Time_1=time.time()-start_time
start_time_2=time.time()
L=range(1000000)
[i**2 for i in L]
Time_2=time.time()-start_time_2
print(Time_2/Time_1)
##numpy yaklaşık 60 kat daha hizlidir.

22.62003892696962


In [4]:
x=np.array([4,5,6,7])
print(x)
print(type(x))
print(x.shape)
print(x.size)
print(x.ndim)
print(x.nbytes)
print(x.dtype)

[4 5 6 7]
<class 'numpy.ndarray'>
(4,)
4
1
32
int64


In [5]:
y=np.array([[1,2,3],[4,5,6]])
print(y)
print(type(y))
print(y.shape)#tuple
print(y.size)
print(y.ndim)
print(y.nbytes)
print(y.dtype)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
6
2
48
int64


In [6]:
z=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[9,8,7]]])
print(z)
print(type(z))
print(z.shape)
print(z.size)
print(z.ndim)
print(z.nbytes)
print(z.dtype)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [9 8 7]]]
<class 'numpy.ndarray'>
(2, 2, 3)
12
3
96
int64


In [7]:
m=np.array([1,2.0,3])
print(m.dtype)

float64


In [8]:
k=np.array([1,2,"3"])
print(k.dtype)

<U21


In [9]:
array=np.array([1,2,3],dtype=np.complex)
print(array)
print(array.dtype)

[1.+0.j 2.+0.j 3.+0.j]
complex128


In [10]:
x=np.array([1,2,3,4],dtype=np.float)
y=np.array(x,dtype=complex)
print(x,"==>",y)

[1. 2. 3. 4.] ==> [1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [11]:
x1=np.array([1,2,3],dtype=np.int)
x2=np.array([1.5,2.7,3.4],dtype=np.float)
print(x1+x2)

[2.5 4.7 6.4]


In [12]:
x=np.array([[5,6,9,3.2,15],[1,2,3,4,5]])
np.save("ndarray_1",x)#kaydetme

In [13]:
y=np.load("ndarray_1.npy")#kaydedileni kullanma
print(y,np.dtype,y.shape)

[[ 5.   6.   9.   3.2 15. ]
 [ 1.   2.   3.   4.   5. ]] <class 'numpy.dtype'> (2, 5)


In [14]:
x=np.zeros((2,3,4),dtype=np.int)
print(x)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [15]:
x=np.ones((2,3,4),dtype=np.int)
print(x)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [16]:
#np.full 
x=np.full((2,3),5)
print(x)
y=10.0*x
print(y)

[[5 5 5]
 [5 5 5]]
[[50. 50. 50.]
 [50. 50. 50.]]


In [17]:
#np.empty() np.fill()
x=np.empty((2,2))
print(x)
x.fill(4)
print(x)

[[1. 2.]
 [3. 4.]]
[[4. 4.]
 [4. 4.]]


In [18]:
x=np.eye(5,4)#birim
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [19]:
x=np.eye(5,4,k=1)#birim
print(x)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
x=np.diag([5,3,2,1])#birim
print(x)
print(np.diag(x))

[[5 0 0 0]
 [0 3 0 0]
 [0 0 2 0]
 [0 0 0 1]]
[5 3 2 1]


In [21]:
x=np.arange(1,10,2)
print(x)

[1 3 5 7 9]


In [22]:
#np.linspace
x=np.linspace(0,15,10)
print(x)

[ 0.          1.66666667  3.33333333  5.          6.66666667  8.33333333
 10.         11.66666667 13.33333333 15.        ]


In [23]:
x=np.arange(32)
y=np.reshape(x,(2,4,4))
print(y)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]


In [24]:
x=np.linspace(0,19,20)
print(x)
y=np.reshape(x,(2,10))
print(y)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]]


In [25]:
z=np.linspace(0,19,20).reshape(2,10)
print(z)

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]]


In [26]:
x=np.random.random((2,3))
print(x)

[[0.15584273 0.58295798 0.92620815]
 [0.37788417 0.53696022 0.46498088]]


In [27]:
x=np.random.randint(0,10,size=(2,3))
print(x)

[[3 9 2]
 [2 0 9]]


## NDArray degistirme ,Insert,Append, Stack and Delete

In [28]:
x=np.arange(0,11,2)
print(x[3])
x=np.arange(0,11,2)
print(x[-1])

6
10


In [29]:
x=np.arange(12).reshape(3,4)
print(x)
print(x[2,3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
11


In [30]:
x=np.arange(10)
print(x)
x=np.delete(x,[0,1])
print(x)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]


In [31]:
x=np.arange(16).reshape(4,4)
print(x)
x=np.delete(x, 2,axis=0)
print(x)
x=np.delete(x, 2,axis=1)
print(x)
x=np.delete(x, [0,2],axis=1)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [12 13 14 15]]
[[ 0  1  3]
 [ 4  5  7]
 [12 13 15]]
[[ 1]
 [ 5]
 [13]]


In [32]:
x=np.arange(16).reshape(4,4)
print(x)
x=np.append(x,[[1,2,3,4]],axis=0)#satıra ekleme
print(x)
x=np.append(x,[[1],[2],[3],[4],[5]],axis=1)#sutuna ekleme
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [ 1  2  3  4]]
[[ 0  1  2  3  1]
 [ 4  5  6  7  2]
 [ 8  9 10 11  3]
 [12 13 14 15  4]
 [ 1  2  3  4  5]]


In [33]:
#np.insert
array=np.arange(10)
print(array)
array=np.insert(array,5,12)
print(array)
array=np.insert(array,6,[13,14,15])
print(array)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 12  5  6  7  8  9]
[ 0  1  2  3  4 12 13 14 15  5  6  7  8  9]


In [34]:
array=np.arange(9).reshape(3,3)
print(array)
array=np.insert(array,1,[5,12,11],axis=0)
print(array)
array=np.insert(array,2,[1,2,3,4],axis=1)
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2]
 [ 5 12 11]
 [ 3  4  5]
 [ 6  7  8]]
[[ 0  1  1  2]
 [ 5 12  2 11]
 [ 3  4  3  5]
 [ 6  7  4  8]]


In [35]:
x=np.arange(3)
print(x)
y=np.arange(9).reshape(3,3)
print(y)
z=np.vstack((x,y))
print(z)
y=y.reshape(9,)
t=np.hstack((x,y))
print(t)

[0 1 2]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 0 1 2 3 4 5 6 7 8]


In [36]:
#Sciling-copy()
x=np.arange(10)
print(x)
print(x[2:6])
print(x[2:])
print(x[:6])
print(x[0:])
print(x[2:-3])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5]
[2 3 4 5 6 7 8 9]
[0 1 2 3 4 5]
[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6]


In [37]:
x=np.arange(25).reshape(5,5)
print(x)
y=x[0:3,1:4]
print(y)
z=x[2:]
print(z)
t=x[:,3:]
print(t)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]
 [23 24]]


In [38]:
array=np.arange(9).reshape(3,3)
print(array)
y=array[1:2,0:2]
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4]]


In [39]:
array=np.arange(16).reshape(4,4)
print(array)
y=np.copy(array[0:3,1:3])
print(y)
print(np.shares_memory(array,y))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
False


In [40]:
#Fancy, Boolean Indexing


In [41]:
x=np.linspace(1,21,11)
y=np.array([2,4,7])
print(x)
print(y)
print(x[y])
x=np.arange(25).reshape(5,5)
print(x)
y=np.array([1,2])
print(y)
print(x[y,:])
print(x[:,y])

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21.]
[2 4 7]
[ 5.  9. 15.]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[1 2]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]
 [21 22]]


In [42]:
z=x[y,:]
z[0,0]=100
print(z)
print(x)
print(np.shares_memory(x,z))

[[100   6   7   8   9]
 [ 10  11  12  13  14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
False
